name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies 
        run: npm install  
      - name: Check Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Install Playwright browsers
        run: npx playwright install
      - name: Install Playwright dependencies
        run: sudo npx playwright install-deps
      - name: Test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000    
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Notify success
        if: ${{ success() }}
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: info
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          details: "🎉 Deployment succeeded for commit ${{ github.sha }} on branch ${{ github.ref }}."

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          default_bump: patch
          tag_prefix: ""
          release_branches: main
      - name: Notify success
        if: ${{ success() }}
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: info
          details: "🎉 New version tagged and pushed: ${{ github.ref }}."
      - name: Notify failure
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: error
          details: "❌ Deployment failed for commit ${{ github.sha }} on branch ${{ github.ref }}. Please check the logs for details."